[package]
name = "cfspeedtest"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
regex = "1.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
