[package]
name = "cfspeedtest"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.0"
reqwest = { version = "0.11.1", features = ["blocking"] }
openssl = { version = "0.10.45", features = ["vendored"]}
