name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    # Use Ubuntu 20.04 here, because latest (22.04) uses OpenSSL v3.
    # Currently OpenSSL v3 causes compile issues with openssl-sys
    # see: https://github.com/seanmonstar/reqwest/blob/master/.github/workflows/ci.yml#L207
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        include:
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-20.04
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cfspeedtest
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
